apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: registry.31j.de/lab/testing
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: 31j.de
